export const nijisanji = [
  {
    name: 'Petra Gurin',
    ytId: 'UCgA2jKRkqpY_8eysPUs8sjw',
    chName: 'Petra Gurin【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/InPLoP8e6-x9F_3kMiaDpxbG8gmloA-eOYwM_M2fi6_jbjpLGZtWUUdH9XVUE6vsNl0QAe_7mA=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 2nd wave'],
    twitter: 'Petra_Gurin',
    aliases: ['petra'],
  },
  {
    name: 'Elira Pendora',
    ytId: 'UCIeSUTOTkF9Hs7q3SGcO-Ow',
    chName: 'Elira Pendora 【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/rBUqVoyIti32FfNnqy0cxMBZOLyvTmGoVjOqgMuvAjRdaEZR9EVAKQQ7atlIAJaCdmAgt_9OjlM=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 1st wave'],
    twitter: 'EliraPendora',
    aliases: ['elira'],
  },
  {
    name: 'Pomu Rainpuff',
    ytId: 'UCP4nMSTdwU1KqYWu3UH5DHQ',
    chName: 'Pomu Rainpuff 【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/vzTQuBjtI_ZJ5RFkxolmnaP07ChJEcJLJJtruTDsNvf49EIkEPGfJat19O4FFIvW1Pu-ljItrw=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 1st wave'],
    twitter: 'PomuRainpuff',
    aliases: ['pomu'],
  },
  {
    name: 'Finana Ryugu',
    ytId: 'UCu-J8uIXuLZh16gG-cT1naw',
    chName: 'Finana Ryugu 【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/qW1s1IovgkP8pZ0YRBJ6orFElmFzkRb_ActIKUowfHJGjF_xRR5RPlvKhXBRT06o4_u_j9mDczg=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 2nd wave'],
    twitter: 'FinanaRyugu',
    aliases: ['finana'],
  },
  {
    name: 'Selen Tatsuki',
    ytId: 'UCV1xUwfM2v2oBtT3JNvic3w',
    chName: 'Selen Tatsuki 【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/OLpUvHlKRG9RrHxJo_QV0OYrh_bvUPpKI-MK80f8SBA2uTmre_Kx1Gq9lZhU6rmOEYlvo33Pp3M=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 2nd wave'],
    twitter: 'selen_tatsuki',
    aliases: ['selen'],
  },
  {
    name: 'Rosemi Lovelock',
    ytId: 'UC4WvIIAo89_AzGUh1AZ6Dkg',
    chName: 'Rosemi Lovelock【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/g38pfFWO4nWf-6X1U4NvJODSUEonEJpgEP-J-_tQzERyxJnSuJy5S4cGy5G-dlaQ9PZdWabEBNU=s176-c-k-c0x00ffffff-no-rj-mo',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 2nd wave'],
    twitter: 'Rosemi_Lovelock',
    aliases: ['Rosemi'],
  },
  {
    name: 'Ban Hada',
    ytId: 'UCLjx3lqIkYkPCBJop8czJ2A',
    chName: '반하다 / Ban Hada 【NIJISANJI KR】',
    picture:
      'https://yt3.ggpht.com/ytc/AKedOLRroQSThdusiJTmBVq-V1Tl7XHbox_i2fB6vodX=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji KR', 'Nijisanji KR 5th gen'],
    twitter: 'BanHada2434',
    aliases: ['Hada'],
  },
  {
    name: 'Nina Kosaka',
    ytId: 'UCkieJGn3pgJikVW8gmMXE2w',
    chName: 'Nina Kosaka【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/-JRODQIYAdJjCTGJrqJtyypBPMmkegGUMle_V3o2uF6OSbBWWVLvPnPCnJDXwI-7AilZUFhoqg=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 3rd wave'],
    twitter: 'NinaKosaka',
    aliases: ['Nina'],
  },
  {
    name: 'Millie Parfait',
    ytId: 'UC47rNmkDcNgbOcM-2BwzJTQ',
    chName: 'Millie Parfait【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/RDcSwXxXz8yWZM3hwyulgUwwHMVYGSGdFxTf0PXOAPlSKzs9_g4sXsw-dJlYb1wKaPvkiAZo=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 3rd wave'],
    twitter: 'MillieParfait',
    aliases: ['Millie'],
  },
  {
    name: 'Enna Alouette',
    ytId: 'UCR6qhsLpn62WVxCBK1dkLow',
    chName: 'Enna Alouette【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/CUcCKimOq7plRLyNboLNlCSxFH0jS-CZ1SV7_S3fwwVAg4tkOXNOcsGvi-128XV4FEsUWZaPCA=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 3rd wave'],
    twitter: 'EnnaAlouette',
    aliases: ['Enna'],
  },
  {
    name: 'Reimu Endou',
    ytId: 'UCBURM8S4LH7cRZ0Clea9RDA',
    chName: 'Reimu Endou【NIJISANJI EN】',
    picture:
      'https://yt3.ggpht.com/5drj0xMO04Pdpm1Xpqk3fObyHqjHIkGj-inUheg7iOdmpsXaEUJ2zX1jOfX3_wclF8Jd9JLXGQ=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji EN', 'Nijisanji EN 3rd wave'],
    twitter: 'ReimuEndou',
    aliases: ['Reimu'],
  },
  {
    name: 'Machita Chima',
    ytId: 'UCo7TRj3cS-f_1D9ZDmuTsjw',
    chName: 'Machita Chima',
    picture:
      'https://yt3.ggpht.com/ytc/AKedOLTpaFhkNBf2kkuap4nxvCUFDUJJAX2LwyGNjgc59w=s88-c-k-c0x00ffffff-no-rj',
    groups: ['Nijisanji', 'Nijisanji JP'],
    twitter: 'chima_machita23',
    aliases: ['Chima', 'ちま'],
  },
  // luxiem
  {
    name: 'Luca Kaneshiro',
    ytId: 'UC7Gb7Uawe20QyFibhLl1lzA',
    chName: 'Luca Kaneshiro【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Luxiem'],
    twitter: 'luca_kaneshiro',
    aliases: ['Luca'],
  },
  {
    name: 'Shu Yamino',
    ytId: 'UCG0rzBZV_QMP4MtWg6IjhEA',
    chName: 'Shu Yamino【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Luxiem'],
    twitter: 'shu_yamino',
    aliases: ['Shu'],
  },
  {
    name: 'Ike Eveland',
    ytId: 'UC4yNIKGvy-YUrwYupVdLDXA',
    chName: 'Ike Eveland【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Luxiem'],
    twitter: 'ike_eveland',
    aliases: ['Ike'],
  },
  {
    name: 'Mysta Rias',
    ytId: 'UCIM92Ok_spNKLVB5TsgwseQ',
    chName: 'Mysta Rias 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Luxiem'],
    twitter: 'Mysta_Rias',
    aliases: ['Mysta'],
  },
  {
    name: 'Vox Akuma',
    ytId: 'UCckdfYDGrjojJM28n5SHYrA',
    chName: 'Vox Akuma【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Luxiem'],
    twitter: 'Vox_Akuma',
    aliases: ['Vox'],
  },
  // noctyx
  {
    name: 'Sonny Brisko',
    ytId: 'UCuuAb_72QzK0M1USPMEl1yw',
    chName: 'Sonny Brisko 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Noctyx'],
    twitter: 'sonny_brisko',
    aliases: ['Sonny'],
  },
  {
    name: 'Uki Violeta',
    ytId: 'UChJ5FTsHOu72_5OVx0rvsvQ',
    chName: 'Uki Violeta 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Noctyx'],
    twitter: 'uki_violeta',
    aliases: ['Uki'],
  },
  {
    name: 'Alban Knox',
    ytId: 'UCQ1zGxHrfEmmW4CPpBx9-qw',
    chName: 'Alban Knox 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Noctyx'],
    twitter: 'alban_knox',
    aliases: ['Alban', 'Knox'],
  },
  {
    name: 'Fulgur Ovid',
    ytId: 'UCGhqxhovNfaPBpxfCruy9EA',
    chName: 'Fulgur Ovid 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Noctyx'],
    twitter: 'Fulgur_Ovid',
    aliases: ['Fulgur'],
  },
  {
    name: 'Yugo Asuma',
    ytId: 'UCSc_KzY_9WYAx9LghggjVRA',
    chName: 'Yugo Asuma 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'Noctyx'],
    twitter: 'Yugo_Asuma',
    aliases: ['Yugo'],
  },
  {
    name: 'Maria Marionette',
    ytId: 'UCwaS8_S7kMiKA3izlTWHbQg',
    chName: 'Maria Marionette 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'MariaMari0nette',
    aliases: ['Maria'],
  },
  {
    name: 'Kyo Kaneko',
    ytId: 'UCsb-1aJgiJXJH2feV-zlZRw',
    chName: 'Kyo Kaneko 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'KyoKanek0',
    aliases: ['Kyo'],
  },
  {
    name: 'Aia Amare',
    ytId: 'UCN68LoM3khS4gdBMiWJO8WA',
    chName: 'Aia Amare 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'AiaAmare',
    aliases: ['Aia'],
  },
  {
    name: 'Aster Arcadia',
    ytId: 'UCpzxZW5kghGnO5TmAFJQAVw',
    chName: 'Aster Arcadia 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'AsterArcadia',
    aliases: ['Aster'],
  },
  {
    name: 'Scarle Yonaguni',
    ytId: 'UCFgXWZOUZA2oYHNr6qDmsTQ',
    chName: 'Scarle Yonaguni 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'ScarleYonaguni',
    aliases: ['Scarle'],
  },
  {
    name: 'Ren Zotto',
    ytId: 'UCKu59gTZ_rdEmerdx5rV4Yg',
    chName: 'Ren Zotto 【NIJISANJI EN】',
    picture: 'dont put anything here',
    groups: ['Nijisanji', 'Nijisanji EN', 'ILUNA'],
    twitter: 'renzott0',
    aliases: ['Ren'],
  },
  // iluna
] as const
